---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: testserver 
  tasks:
     - name: Transfer executable script script
       command: sh mkdir -p /tmp/mdmscripts
       copy: src=/tmp/mdmscripts/mdmadmin dest=/tmp/mdmscripts mode=0777
 
     - name: Execute the script
       command: sh /tmp/mdmscripts/mdmadmin $action
