---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: testserver 
  tasks:
     - name: create dir on remote machiens
       command: mkdir -p /tmp/mdmscripts
       
     - name: Transfer executable script script
       copy: src=/tmp/mdmscripts/mdmadmin dest=/tmp/mdmscripts mode=0777
 
     - name: Execute the script
       command: sh /tmp/mdmscripts/mdmadmin $task
